// <auto-generated />
using System;
using Ecommerce.DataProvider;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.DataProvider.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230619093543_adding registeruser and registeruseraddress table")]
    partial class addingregisteruserandregisteruseraddresstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.DBClasses.RegisterUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForgetCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterUserAddress_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("registeredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RegisterUserAddress_ID");

                    b.ToTable("registerUsers");
                });

            modelBuilder.Entity("Ecommerce.Domain.DBClasses.RegisterUserAddress", b =>
                {
                    b.Property<int>("RegisterUserAddress_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterUserAddress_ID"));

                    b.Property<int>("RegisterUserAddress_PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("RegisterUserAddress_PostalCode")
                        .HasColumnType("int");

                    b.Property<int>("RegisterUserAddress_city")
                        .HasColumnType("int");

                    b.Property<int>("RegisterUserAddress_country")
                        .HasColumnType("int");

                    b.Property<int>("RegisterUserAddress_state")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RegisterUserAddress_ID");

                    b.ToTable("registerUsersAddress");
                });

            modelBuilder.Entity("Ecommerce.Domain.DBClasses.RegisterUser", b =>
                {
                    b.HasOne("Ecommerce.Domain.DBClasses.RegisterUserAddress", "RegisterUserAddress")
                        .WithMany()
                        .HasForeignKey("RegisterUserAddress_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisterUserAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
